# Generated by Django 6.0.6 on 2026-06-27 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_security', '0001_initial'),
        ('courses', '0004_lesson_download_profiles_lesson_download_window_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HLSPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('ready', 'Prêt'), ('failed', 'Échoué')], default='pending', max_length=12)),
                ('output_dir', models.CharField(blank=True, help_text='Chemin relatif sous MEDIA_ROOT', max_length=500)),
                ('segment_count', models.PositiveIntegerField(default=0)),
                ('segment_duration_seconds', models.PositiveIntegerField(default=6)),
                ('encryption_key_hex', models.CharField(blank=True, max_length=32)),
                ('encryption_iv_hex', models.CharField(blank=True, max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hls_package', to='courses.lesson')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuspiciousActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('devtools_opened', 'Outils de développement ouverts'), ('right_click_blocked', 'Clic droit bloqué'), ('copy_attempt', 'Tentative de copie'), ('tab_blur_during_exam', "Changement d'onglet pendant un examen"), ('screen_recording_suspected', "Enregistrement d'écran suspecté"), ('multiple_login_attempt', 'Tentative de connexion multiple'), ('other', 'Autre')], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.lesson')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspicious_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
