# Generated by Django 6.0.6 on 2026-07-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_security', '0002_hlspackage_suspiciousactivityevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspiciousactivityevent',
            name='event_type',
            field=models.CharField(choices=[('devtools_opened', 'Outils de développement ouverts'), ('right_click_blocked', 'Clic droit bloqué'), ('copy_attempt', 'Tentative de copie'), ('drag_attempt', 'Tentative de glisser-déposer'), ('tab_blur_during_exam', "Changement d'onglet pendant un examen"), ('screen_recording_suspected', "Enregistrement d'écran suspecté"), ('multiple_login_attempt', 'Tentative de connexion multiple'), ('other', 'Autre')], max_length=30),
        ),
    ]
