# Generated by Django 6.0.6 on 2026-06-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_employeeimportbatch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='§25.3 — profil Premium B2C, utilisé pour restreindre certains téléchargements'),
        ),
    ]
