# Generated by Django 5.2.15 on 2026-06-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_mfa_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_iban',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='payout_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Virement bancaire'), ('mobile_money', 'Mobile Money')], help_text='Formateurs uniquement — méthode de versement des revenus', max_length=20),
        ),
    ]
