# Generated by Django 5.2.15 on 2026-06-29 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_bank_account_name_user_bank_iban_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, default='slate', max_length=20)),
                ('is_system', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-is_system', 'key'],
            },
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
