# Generated by Django 5.2.15 on 2026-06-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_roledefinition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrateur'), ('company_admin', 'Administrateur Entreprise'), ('training_center_admin', 'Admin Centre de Formation'), ('hr', 'RH'), ('manager', 'Manager'), ('employee', 'Employé'), ('trainer', 'Formateur'), ('student', 'Apprenant (B2C)')], default='student', max_length=30),
        ),
    ]
