# Generated by Django 6.0.6 on 2026-08-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='partner_default_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Partenaires vidéo — taux de partage de revenus par défaut (ex: 30 ou 40), pré-rempli lors de la liaison à un cours mais modifiable par cours.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='payout_method',
            field=models.CharField(blank=True, choices=[('bank_transfer', 'Virement bancaire'), ('mobile_money', 'Mobile Money')], help_text='Formateurs/partenaires — méthode de versement des revenus', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrateur'), ('company_admin', 'Administrateur Entreprise'), ('training_center_admin', 'Admin Centre de Formation'), ('hr', 'RH'), ('manager', 'Manager'), ('employee', 'Employé'), ('trainer', 'Formateur'), ('student', 'Apprenant (B2C)'), ('partner', 'Partenaire vidéo')], default='student', max_length=30),
        ),
    ]
