# Generated by Django 5.2.15 on 2026-06-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_alter_certificatetemplate_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='accent_color',
            field=models.CharField(default='#0F4C81', max_length=7),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='body_paragraph',
            field=models.TextField(default='Pour avoir suivi avec succès la formation {course_title}, démontrant ainsi engagement et maîtrise des compétences visées.'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='footer_website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='intro_text',
            field=models.CharField(default='Est décerné avec distinction à', max_length=150),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='org_logo',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/templates/logos/'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='org_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='signer1_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='signer1_signature',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/templates/signatures/'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='signer1_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='signer2_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='signer2_signature',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/templates/signatures/'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='signer2_title',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='title_text',
            field=models.CharField(default='CERTIFICAT DE FORMATION', max_length=150),
        ),
    ]
