# Generated by Django 5.2.15 on 2026-06-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificatetemplate_accent_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='body_font_size',
            field=models.PositiveSmallIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='intro_font_size',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='org_name_font_size',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='title_font_size',
            field=models.PositiveSmallIntegerField(default=28),
        ),
    ]
