# Generated by Django 5.2.15 on 2026-06-29 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_certificatetemplate_body_font_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='gap_after_content',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='gap_after_header',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='gap_after_title',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
