# Generated by Django 6.0.6 on 2026-06-27 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_download_profiles_lesson_download_window_end_and_more'),
        ('virtual_classes', '0002_alter_virtualclassquestion_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualclass',
            name='chapter',
            field=models.ForeignKey(blank=True, help_text='Si renseigné, la présence à cette classe peut conditionner le déverrouillage du chapitre suivant (§24.2)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_classes', to='courses.chapter'),
        ),
        migrations.CreateModel(
            name='AttendanceSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signed_name', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('signature_hash', models.CharField(max_length=128)),
                ('signed_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_signatures', to=settings.AUTH_USER_MODEL)),
                ('virtual_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_signatures', to='virtual_classes.virtualclass')),
            ],
            options={
                'unique_together': {('virtual_class', 'user')},
            },
        ),
    ]
