# Generated by Django 6.0.6 on 2026-06-27 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiclient',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ssoconfiguration',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='webhookendpoint',
            options={'ordering': ['-created_at']},
        ),
    ]
