# Generated by Django 6.0.6 on 2026-06-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0002_alter_courseprogressionsettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseprogressionsettings',
            name='attendance_signature_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courseprogressionsettings',
            name='virtual_class_attendance_required',
            field=models.BooleanField(default=False),
        ),
    ]
