# Generated by Django 6.0.6 on 2026-08-27 22:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0004_learning_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='xapistatement',
            index=models.Index(fields=['object_type', 'timestamp'], name='prog_xapi_type_ts_idx'),
        ),
        migrations.AddIndex(
            model_name='xapistatement',
            index=models.Index(fields=['object_type', 'object_id', 'timestamp'], name='prog_xapi_type_obj_ts_idx'),
        ),
    ]
