# Generated by Django 6.0.6 on 2026-07-31 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_plan_type_billing_cycles_user_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_agent_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('reglement_interieur', 'Règlement intérieur'), ('onboarding', 'Intégration / Onboarding'), ('general', 'Information générale')], default='general', max_length=30)),
                ('content_type', models.CharField(choices=[('text', 'Texte'), ('pdf', 'Document PDF'), ('video', 'Vidéo')], default='text', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('text_body', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='hr_agent/documents/')),
                ('video_url', models.URLField(blank=True)),
                ('keywords', models.CharField(blank=True, help_text="Mots-clés séparés par des virgules, utilisés par l'agent pour retrouver ce contenu.", max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_resources', to='tenants.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text="Laisser vide pour un contenu valable dans toute l'entreprise (ex: règlement intérieur).", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_resources', to='tenants.department')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_resources', to='tenants.service')),
            ],
            options={
                'ordering': ['category', 'order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('agent', 'Agent')], max_length=10)),
                ('content', models.TextField(blank=True)),
                ('intent', models.CharField(blank=True, max_length=30)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='hr_agent.agentconversation')),
                ('resources', models.ManyToManyField(blank=True, related_name='+', to='hr_agent.agentresource')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobDescriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('department_name', models.CharField(blank=True, max_length=255)),
                ('manager_name', models.CharField(blank=True, max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('missions', models.JSONField(blank=True, default=list)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='hr_agent/fiches_poste/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_description_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
