# Generated by Django 5.2.15 on 2026-06-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(default='LMS PRO', max_length=150)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('default_currency', models.CharField(default='XOF', max_length=3)),
                ('default_commission_rate', models.DecimalField(decimal_places=2, default=30, help_text='Pourcentage prélevé par la plateforme sur les ventes de cours des formateurs (%)', max_digits=5)),
                ('b2c_signup_enabled', models.BooleanField(default=True)),
                ('featured_course_ids', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètres plateforme',
                'verbose_name_plural': 'Paramètres plateforme',
            },
        ),
    ]
