# Generated by Django 6.0.6 on 2026-08-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_platformsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformsettings',
            name='revenue_share_launch_date',
            field=models.DateField(blank=True, help_text="Premier mois éligible au partage de revenus partenaires — aucune donnée de vues horodatée n'existe avant cette date, la clôture d'un mois antérieur est refusée.", null=True),
        ),
    ]
