# Generated by Django 6.0.6 on 2026-06-27 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonresource',
            options={'ordering': ['-created_at']},
        ),
    ]
