# Generated by Django 6.0.6 on 2026-06-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lessonresource_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='download_profiles',
            field=models.JSONField(blank=True, default=list, help_text="§25.3 — profils autorisés au téléchargement (ex: ['premium','company','hr']). Vide = tous les inscrits."),
        ),
        migrations.AddField(
            model_name='lesson',
            name='download_window_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='download_window_start',
            field=models.DateTimeField(blank=True, help_text='§25.3 — téléchargement limité à une période', null=True),
        ),
        migrations.AddField(
            model_name='lessonresource',
            name='download_profiles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lessonresource',
            name='download_window_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonresource',
            name='download_window_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
