# Generated by Django 6.0.6 on 2026-06-28 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_download_profiles_lesson_download_window_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='scorm_extracted_path',
            field=models.CharField(blank=True, help_text='Chemin relatif sous MEDIA_ROOT du paquet décompressé', max_length=500),
        ),
        migrations.AddField(
            model_name='lesson',
            name='scorm_identifier',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lesson',
            name='scorm_version',
            field=models.CharField(blank=True, help_text="'1.2' ou '2004', détecté depuis le manifeste", max_length=10),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='scorm_launch_url',
            field=models.CharField(blank=True, help_text='Résolu automatiquement depuis imsmanifest.xml', max_length=500),
        ),
        migrations.CreateModel(
            name='ScormRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cmi_data', models.JSONField(blank=True, default=dict)),
                ('lesson_status', models.CharField(choices=[('not_attempted', 'Non commencé'), ('incomplete', 'Incomplet'), ('completed', 'Terminé'), ('passed', 'Réussi'), ('failed', 'Échoué'), ('browsed', 'Consulté')], default='not_attempted', max_length=20)),
                ('score_raw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('suspend_data', models.TextField(blank=True)),
                ('total_time_seconds', models.PositiveIntegerField(default=0)),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorm_registrations', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorm_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
