# Generated by Django 5.2.15 on 2026-06-28 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lessonquestion_lessonanswer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, help_text='Intitulé si aucun cours existant.', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('urgency', models.CharField(choices=[('low', 'Faible'), ('medium', 'Normale'), ('high', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée')], default='pending', max_length=10)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, help_text='Formation spécifique demandée (facultatif).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_requests', to='courses.course')),
                ('for_user', models.ForeignKey(blank=True, help_text='Si vide, la demande est pour soi-même.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_requests_received', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_requests_submitted', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
