# Generated by Django 6.0.6 on 2026-06-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_training_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='transcript',
            field=models.TextField(blank=True, help_text='§Sous-titrage automatique — transcription générée par IA'),
        ),
    ]
