# Generated by Django 6.0.6 on 2026-07-31 22:15

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_lessonreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='document_file',
            field=models.FileField(blank=True, null=True, storage=apps.core.storage.r2_media_storage, upload_to='courses/documents/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, null=True, storage=apps.core.storage.r2_media_storage, upload_to='courses/videos/'),
        ),
    ]
