# Generated by Django 6.0.6 on 2026-08-27 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_lesson_document_file_alter_lesson_video_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='revenue_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_revenue_share', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='revenue_share_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pourcentage du revenu global du cours reversé à revenue_partner (ex: 30.00 ou 40.00)', max_digits=5, null=True),
        ),
    ]
