# Generated by Django 6.0.6 on 2026-06-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_alter_badge_options_alter_challenge_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='criteria_type',
            field=models.CharField(choices=[('course_completion', 'Complétion de formation'), ('xp_threshold', "Seuil d'XP"), ('streak', 'Série de connexions'), ('skill_mastery', 'Maîtrise de compétence'), ('custom', 'Personnalisé')], default='custom', max_length=20),
        ),
    ]
