# Generated by Django 6.0.6 on 2026-06-27 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('courses', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='chapter',
            field=models.ForeignKey(blank=True, help_text='Vide = évaluation au niveau de la formation entière (examen final)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.chapter'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='assessmentattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='attempt',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submission', to='assessments.assessmentattempt'),
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.assessmentattempt'),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='assessments.question'),
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='assessments.question'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='tenants.company'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.questionbank'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='question_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='assessments.questionbank'),
        ),
        migrations.AddField(
            model_name='questionchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assessments.question'),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='selected_choices',
            field=models.ManyToManyField(blank=True, related_name='+', to='assessments.questionchoice'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentquestion',
            unique_together={('assessment', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='attemptanswer',
            unique_together={('attempt', 'question')},
        ),
    ]
