# Generated by Django 5.2.15 on 2026-06-28 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_company_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('b2c', 'Centre de formation (B2C)'), ('enterprise', 'Entreprise')], default='enterprise', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', '1 mois'), ('quarterly', '3 mois'), ('semi_annual', '6 mois'), ('yearly', '12 mois (1 an)')], default='monthly', max_length=20),
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expirée'), ('cancelled', 'Annulée')], default='active', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_subscriptions', to='tenants.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
