# Generated by Django 6.0.6 on 2026-08-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_lesson_document_file_alter_lesson_video_file'),
        ('tenants', '0004_plan_type_billing_cycles_user_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='included_courses',
            field=models.ManyToManyField(blank=True, help_text='Cours débloqués par ce plan quand is_global est désactivé.', related_name='subscription_plans', to='courses.course'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_global',
            field=models.BooleanField(default=True, help_text='Si coché, ce plan donne accès à tout le catalogue. Sinon, uniquement aux cours listés dans included_courses.'),
        ),
    ]
