# Generated by Django 6.0.6 on 2026-08-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_subscriptionplan_included_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', '1 mois'), ('quarterly', '3 mois'), ('semi_annual', '6 mois'), ('yearly', '12 mois (1 an)'), ('lifetime', 'À vie')], default='monthly', max_length=20),
        ),
    ]
