# Generated by Django 5.2.15 on 2026-06-28 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_cartitem_course_bundle_and_more'),
        ('payments', '0003_payout_payoutitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='catalog.bundle'),
        ),
    ]
