# Generated by Django 5.2.15 on 2026-06-28 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_orderitem_bundle'),
        ('tenants', '0003_company_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tenants.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='provider',
            field=models.CharField(choices=[('manual', 'Manuel'), ('cash', 'Espèces'), ('stripe', 'Stripe'), ('cinetpay', 'CinetPay (Mobile Money/Carte)'), ('paypal', 'PayPal')], max_length=20),
        ),
    ]
