# Generated by Django 6.0.6 on 2026-09-09 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_subscription_plan_receipt'),
        ('tenants', '0007_team_plan_team_subscription_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Renseigné pour un abonnement souscrit au niveau équipe.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tenants.team'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('course_purchase', 'Achat de formation'), ('subscription', 'Abonnement')], default='course_purchase', max_length=20),
        ),
    ]
