# Generated by Django 6.0.6 on 2026-09-10 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_order_team_alter_order_order_type'),
        ('tenants', '0007_team_plan_team_subscription_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='covered_team_ids',
            field=models.JSONField(blank=True, default=list, help_text='Abonnement entreprise : ids des équipes à rattacher explicitement une fois le paiement confirmé.'),
        ),
        migrations.AlterField(
            model_name='order',
            name='team',
            field=models.ForeignKey(blank=True, help_text="Obsolète — les équipes sont désormais rattachées à l'abonnement de leur entreprise.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='tenants.team'),
        ),
    ]
