# Generated by Django 6.0.6 on 2026-06-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_paths', '0002_alter_learningpath_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpath',
            name='certificate_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
