# Generated by Django 5.2.15 on 2026-06-28 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_paths', '0003_learningpath_certificate_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='join_url',
            field=models.URLField(blank=True, help_text='Lien de connexion pour les sessions en ligne'),
        ),
    ]
