# Generated by Django 6.0.6 on 2026-06-27 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluation360campaign',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='individualdevelopmentplan',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='jobrole',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pdiobjective',
            options={'ordering': ['-created_at']},
        ),
    ]
