# Generated by Django 5.2.15 on 2026-06-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_analytics', '0002_alter_evaluation360campaign_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluation360response',
            name='evaluator_type',
            field=models.CharField(choices=[('self', 'Auto-évaluation'), ('manager', 'Manager'), ('peer', 'Collègue'), ('hr', 'RH'), ('final', 'Évaluation finale')], max_length=10),
        ),
    ]
