# Generated by Django 6.0.6 on 2026-06-27 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('courses', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='courses.course'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='applicable_courses',
            field=models.ManyToManyField(blank=True, related_name='coupons', to='courses.course'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='tenants.company'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='courses.course'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'course')},
        ),
    ]
