# Generated by Django 5.2.15 on 2026-06-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_cartitem_course_bundle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
