# Generated by Django 6.0.6 on 2026-06-27 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='learninggroup',
            options={'ordering': ['-created_at']},
        ),
    ]
